name: loveyoga
favicon: null
layout_spectrum: 0.6465931120328605
typography_spectrum: 0.21616150601767004
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.998990735039115
  lightness: 0.3790690388996154
  saturation: 0.8206862155348063
  rhythmicContrast: 0.36777524347417057
purpose: []
