name: loveyoga
favicon: null
layout_spectrum: 0.94152
typography_spectrum: 0.32862
title: 'Discover how I changed my life with yoga '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f1f1'
    - '#0c0d12'
    - '#40a4a2'
    - '#8bccb4'
    - '#2a6f7e'
  brandStrength: 0.875
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
