name: loveyoga
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48722
title: '♡ Welcome Yoga Lover ♡ '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b6b6b8'
    - '#250514'
    - '#b57188'
    - '#89d8e5'
  brandStrength: 0.875
  lightness: 0.9375
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
