name: loveyoga
favicon: null
layout_spectrum: 0.94152
typography_spectrum: 0.66778
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0077a1'
    - '#070e0e'
    - '#663125'
    - '#cadee3'
    - '#9d614b'
  brandStrength: 0.875
  lightness: 0.6875
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
